services:

  postgres:
    image: postgres:15
    container_name: insurance-postgres
    restart: always
    environment:
      POSTGRES_DB: insurance_db
      POSTGRES_USER: rubindev
      POSTGRES_PASSWORD: rubindev!1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
